<?php
/**
 * @file
 * Basic CRL 2 Breakpoints module
 * Author: Jeremy Pitt
 */

// Specify the CRL2 Theme Key
define('CRL2_THEME_KEY', 'cr_layout_v2');

/**
 * Implements hook_preprocess_page
 * Simply hooks into the page preprocess and exposes the breakpoints variable
 */
function crl2_breakpoints_preprocess_html($vars) {
	// We can safely assume breakpoints is there but let's still check if the function exists before proceeding
	if(!function_exists('breakpoints_breakpoint_load_all')) return;

	// Load the breakpoints
	$breakpoints = breakpoints_breakpoint_load_all(CRL2_THEME_KEY);

	// Create the exposed breakPint JS settings
	$breakpoints_js_setting = array();
	foreach($breakpoints as $breakpoint) {
		$breakpoints_js_setting[$breakpoint->name] = $breakpoint->breakpoint;
	}

	// Add to JS under crl2 namespace Drupal.settings.crl2.breakpoints
	drupal_add_js(array('crl2' => array('breakpoints' => $breakpoints_js_setting)), 'setting');
}